name: "AWS CodeArt deploy"
description: "CodeArt into AWS Cloud"
inputs:
  mvndir: 
    description: "mvn dir"
    required: true
  awsowner: 
    description: "awsowner"
    required: true
  region: 
    description: "Region name, for example 'eu-west-3'"
    required: true
  aws_access_key_id: 
    description: "aws_access_key_id to login"
    required: true
  aws_secret_access_key: 
    description: "The aws_secret_access_key to connect into AWS Cloud"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.mvndir }}
    - ${{ inputs.awsowner }}
    - ${{ inputs.region }}
    - ${{ inputs.aws_access_key_id }}
    - ${{ inputs.aws_secret_access_key }}
branding:
  color: 'green'
  icon: 'at-sign'